### ISSUE TITLE
thin lines look bad.

### ISSUE THREAD

**Issue by setanarut** [godot-extended-libraries/godot-antialiased-line2d#3]
in demo project;
width = 1 , no antialiasing
width = 2 up to 10,  weird antialiasing

<img width="797" alt="Ekran Resmi 2022-03-13 01 14 32" src="https://user-images.githubusercontent.com/36481442/158036942-51634611-77d7-4b11-8e12-b9b5b154ef33.png">

**Comment by Calinou** [comment]
> width = 1 , no antialiasing

Unfortunately, it's technically impossible for antialiasing to be done with 1 pixel-wide lines with the custom mipmaps approach.

> width = 2 up to 10, weird antialiasing

The 2 pixel-line also doesn't have great antialiasing (only one of its sides is antialiased), which is also a technical limitation of this approach.

**Comment by Calinou** [comment]
This is now documented with https://github.com/godot-extended-libraries/godot-antialiased-line2d/commit/232840ea9d9eb86dde9592f74b19670eb9f9e420, closing.
