### ISSUE TITLE
AntialiasedPolygon2D - polygon setter not working

### ISSUE THREAD

**Issue by klianc09** [godot-extended-libraries/godot-antialiased-line2d#6]
Setting the 'polygon' property on a AntialiasedPolygon2D (or AntialiasedRegularPolygon2D) can (and will) result in an error.
`$polygon2d.polygon = points`

This is due to the setter in 'antialiased_polygon2d.gd' accessing the old value instead of the new value.

changing
`		line_2d.points = AntialiasedLine2D.construct_closed_line(polygon)`
to
`		line_2d.points = AntialiasedLine2D.construct_closed_line(value)`
will fix this.
(same with AntialiasedRegularPolygon2D)

**Comment by Calinou** [comment]
Fixed by https://github.com/godot-extended-libraries/godot-antialiased-line2d/commit/c7cde8905ae79718d9e5a8cd625bb53b4b464b9e.
