### ISSUE TITLE
"AntialiasedLine2DTexture" isn't declared in the current scope

### ISSUE THREAD

**Issue by VanDeiMin** [godot-extended-libraries/godot-antialiased-line2d#7]
how can I fix it?
Is it AntialiasedLine2DTexture class missing?
best regards
van
SCRIPT ERROR: Parse Error: The identifier "AntialiasedLine2DTexture" isn't declared in the current scope.
          at: GDScript::reload (res://addons/antialiased_line2d/antialiased_line2d.gd:7)
SCRIPT ERROR: Parse Error: The identifier "AntialiasedLine2DTexture" isn't declared in the current scope.
          at: GDScript::reload (res://addons/antialiased_line2d/antialiased_regular_polygon2d.gd:21)
SCRIPT ERROR: Parse Error: The identifier "AntialiasedLine2DTexture" isn't declared in the current scope.
          at: GDScript::reload (res://addons/antialiased_line2d/antialiased_line2d.gd:7)
Refreshing plugin: antialiased_line2d
SCRIPT ERROR: Parse Error: The class "AntialiasedLine2D" couldn't be fully loaded (script error or cyclic dependency).
          at: GDScript::reload (res://addons/antialiased_line2d/antialiased_regular_polygon2d.gd:82)

**Comment by OmarShehata** [comment]
@VanDeiMin what version of Godot are you using? If Godot 4, it isn't supported, see https://github.com/godot-extended-libraries/godot-antialiased-line2d/issues/5

If Godot 3...how did you install the plugin? Through the asset library or manually? That sounds like the autoload isn't setup. You could try the manual installation (or vice versa, the asset library install)

**Comment by Calinou** [comment]
> If Godot 3...how did you install the plugin? Through the asset library or manually? That sounds like the autoload isn't setup. You could try the manual installation (or vice versa, the asset library install)

The error message with `script error or cyclic dependency` only exists in 3.x, not 4.x.

@VanDeiMin Which exact Godot version are you using, and how did you install the add-on?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version and latest add-on version.

**Comment by eliacanavera1111** [comment]
Hi! I use godot 4.2.2 and installed the plugin here: https://github.com/OmarShehata/godot-antialiased-line2d/archive/refs/heads/master.zip. But when I enable it from the project settings it gives me these errors:
```
  res://addons/antialiased_line2d/antialiased_line2d.gd:6 - Parse Error: Identifier "AntialiasedLine2DTexture" not declared in the current scope.
  res://addons/antialiased_line2d/antialiased_polygon2d.gd:16 - Parse Error: Identifier "AntialiasedLine2DTexture" not declared in the current scope.
  res://addons/antialiased_line2d/antialiased_regular_polygon2d.gd:19 - Parse Error: Identifier "AntialiasedLine2DTexture" not declared in the current scope.
  res://addons/antialiased_line2d/plugin.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2726 - Failed to load script "res://addons/antialiased_line2d/plugin.gd" with error "Compilation failed". (User)
```
