### ISSUE TITLE
Line2Ds Transparency Overlap

### ISSUE THREAD

**Issue by eliacanavera1111** [godot-extended-libraries/godot-antialiased-line2d#9]
Hi! First of all, thanks for yesterday's update! 😄 

I'm having this problem: [link to the reddit discussion](https://www.reddit.com/r/godot/comments/l4vxiw/comment/lahps8c/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button). So I'm trying to solve with this addon, since in the README Features it says: "Supports opaque and translucent Line2Ds with any joint and cap type (**including multiple overlapping Line2Ds**)".

But it seems that simply using AntialiasedLine2Ds instead of Line2Ds doesn't solve the problem, is there something specific to set?
Or is the addon not intended to solve this kind of problem? Thanks in advance.

**Comment by Calinou** [comment]
This add-on has no specific solution to this problem, however, Godot 4.0 and later have a built-in solution for this.

You need to add the Line2D (or AntialiasedLine2D) as the child of a CanvasGroup node, then modulate the CanvasGroup node instead of modulating the Line2D.
